name: Daily CP Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * *"   # 9 PM IST

jobs:
  auto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Gemini SDK
        run: pip install google-generativeai

      - name: Set TODAY variable
        run: echo "TODAY=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Generate AI Summary
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python ai/summarize.py

      - name: Commit & Push
        run: |
          git config --global user.name "Himanshu-Adhikari"
          git config --global user.email "adhikarihimanshu393@gmail.com"
          git add .
          git commit -m "Daily CP | $TODAY" || echo "No changes"
          git push